# Generated by Django 5.2.3 on 2025-07-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', '-priority', 'due_date'], 'verbose_name': 'مهمة', 'verbose_name_plural': 'المهام'},
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'عالية'), ('M', 'متوسطة'), ('L', 'منخفضة')], default='M', max_length=1, verbose_name='الأولوية'),
        ),
    ]
