# Generated by Django 5.2.3 on 2025-07-10 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'expiration_date'], 'verbose_name': 'مهمة', 'verbose_name_plural': 'المهام'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ/وقت الانتهاء'),
        ),
    ]
